// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeddependencytouserfromportfolio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddependencytouserfromportfolio));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061608532_changed-dependency-to-user-from-portfolio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
