// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedmappostandtagentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedmappostandtagentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041749530_changed-map-post-and-tag-entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
