// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddependencytoportfoliofromuserasonetomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddependencytoportfoliofromuserasonetomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061641251_added-dependency-to-portfolio-from-user-as-one-to-many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
