// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedtypetorssfeeds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtypetorssfeeds));
        
        string IMigrationMetadata.Id
        {
            get { return "201707030717239_added-type-to-rss-feeds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
