// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedimagetochiefuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedimagetochiefuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201706301444062_added-image-to-chief-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
