// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class disablecascadeondeletetopostfromcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(disablecascadeondeletetopostfromcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051357016_disable-cascade-on-delete-to-post-from-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
