// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeddependencytochiefuserfromportfolioasonуtomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddependencytochiefuserfromportfolioasonуtomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071859418_changed-dependency-to-chiefuser-from-portfolio-as-onу-to-many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
