// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allownullabletouserandprojects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allownullabletouserandprojects));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061446214_allow-nullable-to-user-and-projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
