// <auto-generated />
namespace Rhythm.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rebuildalldatabse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rebuildalldatabse));
        
        string IMigrationMetadata.Id
        {
            get { return "201706072008174_rebuild-all-databse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
