//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhythm.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogUser()
        {
            this.DogRoles = new HashSet<DogRole>();
        }
    
        public int ID { get; set; }
        public string NameUser { get; set; }
        public string PasswordUser { get; set; }
        public string EmailUser { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public System.DateTime LastVisitDate { get; set; }
        public byte[] AvatarPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogRole> DogRoles { get; set; }
    }
}
